// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: capturemessage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Direction of a SIP message relative to the dialog's two parties.
type SipDirection int32

const (
	SipDirection_SIP_DIR_UNKNOWN          SipDirection = 0
	SipDirection_SIP_DIR_CALLER_TO_CALLEE SipDirection = 1 // TransactionFlow::C2A
	SipDirection_SIP_DIR_CALLEE_TO_CALLER SipDirection = 2 // TransactionFlow::A2C
)

// Enum value maps for SipDirection.
var (
	SipDirection_name = map[int32]string{
		0: "SIP_DIR_UNKNOWN",
		1: "SIP_DIR_CALLER_TO_CALLEE",
		2: "SIP_DIR_CALLEE_TO_CALLER",
	}
	SipDirection_value = map[string]int32{
		"SIP_DIR_UNKNOWN":          0,
		"SIP_DIR_CALLER_TO_CALLEE": 1,
		"SIP_DIR_CALLEE_TO_CALLER": 2,
	}
)

func (x SipDirection) Enum() *SipDirection {
	p := new(SipDirection)
	*p = x
	return p
}

func (x SipDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SipDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_capturemessage_proto_enumTypes[0].Descriptor()
}

func (SipDirection) Type() protoreflect.EnumType {
	return &file_capturemessage_proto_enumTypes[0]
}

func (x SipDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SipDirection.Descriptor instead.
func (SipDirection) EnumDescriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{0}
}

type IpAddress_Family int32

const (
	IpAddress_IPv4 IpAddress_Family = 0
	IpAddress_IPv6 IpAddress_Family = 1
)

// Enum value maps for IpAddress_Family.
var (
	IpAddress_Family_name = map[int32]string{
		0: "IPv4",
		1: "IPv6",
	}
	IpAddress_Family_value = map[string]int32{
		"IPv4": 0,
		"IPv6": 1,
	}
)

func (x IpAddress_Family) Enum() *IpAddress_Family {
	p := new(IpAddress_Family)
	*p = x
	return p
}

func (x IpAddress_Family) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IpAddress_Family) Descriptor() protoreflect.EnumDescriptor {
	return file_capturemessage_proto_enumTypes[1].Descriptor()
}

func (IpAddress_Family) Type() protoreflect.EnumType {
	return &file_capturemessage_proto_enumTypes[1]
}

func (x IpAddress_Family) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IpAddress_Family.Descriptor instead.
func (IpAddress_Family) EnumDescriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{0, 0}
}

type SipCallFailed_Reason int32

const (
	SipCallFailed_REASON_UNKNOWN  SipCallFailed_Reason = 0
	SipCallFailed_REASON_REJECTED SipCallFailed_Reason = 1 // final non-2xx response (4xx / 5xx / 6xx)
	SipCallFailed_REASON_CANCELED SipCallFailed_Reason = 2 // caller sent CANCEL before the call was answered
	SipCallFailed_REASON_TIMEOUT  SipCallFailed_Reason = 3 // reserved: no final response, dialog reaped by gc() — not yet emitted
)

// Enum value maps for SipCallFailed_Reason.
var (
	SipCallFailed_Reason_name = map[int32]string{
		0: "REASON_UNKNOWN",
		1: "REASON_REJECTED",
		2: "REASON_CANCELED",
		3: "REASON_TIMEOUT",
	}
	SipCallFailed_Reason_value = map[string]int32{
		"REASON_UNKNOWN":  0,
		"REASON_REJECTED": 1,
		"REASON_CANCELED": 2,
		"REASON_TIMEOUT":  3,
	}
)

func (x SipCallFailed_Reason) Enum() *SipCallFailed_Reason {
	p := new(SipCallFailed_Reason)
	*p = x
	return p
}

func (x SipCallFailed_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SipCallFailed_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_capturemessage_proto_enumTypes[2].Descriptor()
}

func (SipCallFailed_Reason) Type() protoreflect.EnumType {
	return &file_capturemessage_proto_enumTypes[2]
}

func (x SipCallFailed_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SipCallFailed_Reason.Descriptor instead.
func (SipCallFailed_Reason) EnumDescriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{15, 0}
}

type Command_Op int32

const (
	Command_TRACK_ADD     Command_Op = 0 // add entries to the list (idempotent)
	Command_TRACK_REMOVE  Command_Op = 1 // remove entries from the list
	Command_TRACK_REPLACE Command_Op = 2 // replace the whole list with entries
	Command_TRACK_QUERY   Command_Op = 3 // return the current list, no mutation
)

// Enum value maps for Command_Op.
var (
	Command_Op_name = map[int32]string{
		0: "TRACK_ADD",
		1: "TRACK_REMOVE",
		2: "TRACK_REPLACE",
		3: "TRACK_QUERY",
	}
	Command_Op_value = map[string]int32{
		"TRACK_ADD":     0,
		"TRACK_REMOVE":  1,
		"TRACK_REPLACE": 2,
		"TRACK_QUERY":   3,
	}
)

func (x Command_Op) Enum() *Command_Op {
	p := new(Command_Op)
	*p = x
	return p
}

func (x Command_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_capturemessage_proto_enumTypes[3].Descriptor()
}

func (Command_Op) Type() protoreflect.EnumType {
	return &file_capturemessage_proto_enumTypes[3]
}

func (x Command_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Op.Descriptor instead.
func (Command_Op) EnumDescriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{18, 0}
}

type IpAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        IpAddress_Family       `protobuf:"varint,1,opt,name=family,proto3,enum=messages.IpAddress_Family" json:"family,omitempty"`
	Relayed       bool                   `protobuf:"varint,2,opt,name=relayed,proto3" json:"relayed,omitempty"`
	Ip            []byte                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IpAddress) Reset() {
	*x = IpAddress{}
	mi := &file_capturemessage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpAddress) ProtoMessage() {}

func (x *IpAddress) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IpAddress.ProtoReflect.Descriptor instead.
func (*IpAddress) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{0}
}

func (x *IpAddress) GetFamily() IpAddress_Family {
	if x != nil {
		return x.Family
	}
	return IpAddress_IPv4
}

func (x *IpAddress) GetRelayed() bool {
	if x != nil {
		return x.Relayed
	}
	return false
}

func (x *IpAddress) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *IpAddress) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// An IPsec ESP security association was bound in vq-core's key store. Published
// only when server.esp.publish-sa-events is on; key bytes present only under
// publish-keys. For coverage monitoring.
type EspSaEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spis          []uint32               `protobuf:"varint,1,rep,packed,name=spis,proto3" json:"spis,omitempty"` // SPIs bound (one per SA)
	Dst           *IpAddress             `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`           // SA destination (owner of the SPI)
	EncAlg        string                 `protobuf:"bytes,3,opt,name=enc_alg,json=encAlg,proto3" json:"enc_alg,omitempty"`
	AuthAlg       string                 `protobuf:"bytes,4,opt,name=auth_alg,json=authAlg,proto3" json:"auth_alg,omitempty"`
	Source        uint32                 `protobuf:"varint,5,opt,name=source,proto3" json:"source,omitempty"`                 // 0 = harvested, 1 = static file
	EncKey        []byte                 `protobuf:"bytes,6,opt,name=enc_key,json=encKey,proto3" json:"enc_key,omitempty"`    // present only under publish-keys
	AuthKey       []byte                 `protobuf:"bytes,7,opt,name=auth_key,json=authKey,proto3" json:"auth_key,omitempty"` // present only under publish-keys
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EspSaEvent) Reset() {
	*x = EspSaEvent{}
	mi := &file_capturemessage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EspSaEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EspSaEvent) ProtoMessage() {}

func (x *EspSaEvent) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EspSaEvent.ProtoReflect.Descriptor instead.
func (*EspSaEvent) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{1}
}

func (x *EspSaEvent) GetSpis() []uint32 {
	if x != nil {
		return x.Spis
	}
	return nil
}

func (x *EspSaEvent) GetDst() *IpAddress {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *EspSaEvent) GetEncAlg() string {
	if x != nil {
		return x.EncAlg
	}
	return ""
}

func (x *EspSaEvent) GetAuthAlg() string {
	if x != nil {
		return x.AuthAlg
	}
	return ""
}

func (x *EspSaEvent) GetSource() uint32 {
	if x != nil {
		return x.Source
	}
	return 0
}

func (x *EspSaEvent) GetEncKey() []byte {
	if x != nil {
		return x.EncKey
	}
	return nil
}

func (x *EspSaEvent) GetAuthKey() []byte {
	if x != nil {
		return x.AuthKey
	}
	return nil
}

type StreamId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Src           *IpAddress             `protobuf:"bytes,1,opt,name=src,proto3" json:"src,omitempty"`
	Dst           *IpAddress             `protobuf:"bytes,2,opt,name=dst,proto3" json:"dst,omitempty"`
	Ssrc          uint32                 `protobuf:"varint,3,opt,name=ssrc,proto3" json:"ssrc,omitempty"`
	Uuid          string                 `protobuf:"bytes,4,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamId) Reset() {
	*x = StreamId{}
	mi := &file_capturemessage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamId) ProtoMessage() {}

func (x *StreamId) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamId.ProtoReflect.Descriptor instead.
func (*StreamId) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{2}
}

func (x *StreamId) GetSrc() *IpAddress {
	if x != nil {
		return x.Src
	}
	return nil
}

func (x *StreamId) GetDst() *IpAddress {
	if x != nil {
		return x.Dst
	}
	return nil
}

func (x *StreamId) GetSsrc() uint32 {
	if x != nil {
		return x.Ssrc
	}
	return 0
}

func (x *StreamId) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// Aggregate of a single metric tracked over a stream's lifetime. Reused for
// jitter, RTT and both MOS scores, all of which carry the same shape. Left at
// proto3 defaults (all zero) when the underlying metric was never initialized.
type MetricStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           float32                `protobuf:"fixed32,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           float32                `protobuf:"fixed32,2,opt,name=max,proto3" json:"max,omitempty"`
	Avg           float32                `protobuf:"fixed32,3,opt,name=avg,proto3" json:"avg,omitempty"`
	Current       float32                `protobuf:"fixed32,4,opt,name=current,proto3" json:"current,omitempty"` // last / instantaneous value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricStats) Reset() {
	*x = MetricStats{}
	mi := &file_capturemessage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricStats) ProtoMessage() {}

func (x *MetricStats) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricStats.ProtoReflect.Descriptor instead.
func (*MetricStats) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{3}
}

func (x *MetricStats) GetMin() float32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *MetricStats) GetMax() float32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *MetricStats) GetAvg() float32 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *MetricStats) GetCurrent() float32 {
	if x != nil {
		return x.Current
	}
	return 0
}

type CaptureStats struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Device                 string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	TotalPacketCounter     uint64                 `protobuf:"varint,2,opt,name=total_packet_counter,json=totalPacketCounter,proto3" json:"total_packet_counter,omitempty"`
	RtpPacketCounter       uint64                 `protobuf:"varint,3,opt,name=rtp_packet_counter,json=rtpPacketCounter,proto3" json:"rtp_packet_counter,omitempty"`
	SipPacketCounter       uint64                 `protobuf:"varint,4,opt,name=sip_packet_counter,json=sipPacketCounter,proto3" json:"sip_packet_counter,omitempty"`
	TruncatedPacketCounter uint64                 `protobuf:"varint,5,opt,name=truncated_packet_counter,json=truncatedPacketCounter,proto3" json:"truncated_packet_counter,omitempty"`
	SrcPortRange           string                 `protobuf:"bytes,6,opt,name=src_port_range,json=srcPortRange,proto3" json:"src_port_range,omitempty"`
	DstPortRange           string                 `protobuf:"bytes,7,opt,name=dst_port_range,json=dstPortRange,proto3" json:"dst_port_range,omitempty"`
	// NIC-level capture-loss counters. Populated by the DPDK capturer from
	// rte_eth_stats (via pcpp DpdkDevice::getStatistics); 0 on the libpcap/HEP paths.
	DroppedHwPacketCounter uint64 `protobuf:"varint,8,opt,name=dropped_hw_packet_counter,json=droppedHwPacketCounter,proto3" json:"dropped_hw_packet_counter,omitempty"`  // dropped by NIC HW: RX queues full
	ErroneousPacketCounter uint64 `protobuf:"varint,9,opt,name=erroneous_packet_counter,json=erroneousPacketCounter,proto3" json:"erroneous_packet_counter,omitempty"`    // erroneous packets (ierrors)
	MbufAllocFailedCounter uint64 `protobuf:"varint,10,opt,name=mbuf_alloc_failed_counter,json=mbufAllocFailedCounter,proto3" json:"mbuf_alloc_failed_counter,omitempty"` // RX mbuf allocation failures
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *CaptureStats) Reset() {
	*x = CaptureStats{}
	mi := &file_capturemessage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureStats) ProtoMessage() {}

func (x *CaptureStats) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureStats.ProtoReflect.Descriptor instead.
func (*CaptureStats) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{4}
}

func (x *CaptureStats) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *CaptureStats) GetTotalPacketCounter() uint64 {
	if x != nil {
		return x.TotalPacketCounter
	}
	return 0
}

func (x *CaptureStats) GetRtpPacketCounter() uint64 {
	if x != nil {
		return x.RtpPacketCounter
	}
	return 0
}

func (x *CaptureStats) GetSipPacketCounter() uint64 {
	if x != nil {
		return x.SipPacketCounter
	}
	return 0
}

func (x *CaptureStats) GetTruncatedPacketCounter() uint64 {
	if x != nil {
		return x.TruncatedPacketCounter
	}
	return 0
}

func (x *CaptureStats) GetSrcPortRange() string {
	if x != nil {
		return x.SrcPortRange
	}
	return ""
}

func (x *CaptureStats) GetDstPortRange() string {
	if x != nil {
		return x.DstPortRange
	}
	return ""
}

func (x *CaptureStats) GetDroppedHwPacketCounter() uint64 {
	if x != nil {
		return x.DroppedHwPacketCounter
	}
	return 0
}

func (x *CaptureStats) GetErroneousPacketCounter() uint64 {
	if x != nil {
		return x.ErroneousPacketCounter
	}
	return 0
}

func (x *CaptureStats) GetMbufAllocFailedCounter() uint64 {
	if x != nil {
		return x.MbufAllocFailedCounter
	}
	return 0
}

type Stream struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StreamId *StreamId              `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// Packet counters
	RtpPacketCounter        uint64 `protobuf:"varint,2,opt,name=rtp_packet_counter,json=rtpPacketCounter,proto3" json:"rtp_packet_counter,omitempty"`
	RtpIllegalPacketCounter uint64 `protobuf:"varint,3,opt,name=rtp_illegal_packet_counter,json=rtpIllegalPacketCounter,proto3" json:"rtp_illegal_packet_counter,omitempty"`
	RtpLostPacketCounter    uint64 `protobuf:"varint,4,opt,name=rtp_lost_packet_counter,json=rtpLostPacketCounter,proto3" json:"rtp_lost_packet_counter,omitempty"`
	RtpDuplicatedCounter    uint64 `protobuf:"varint,5,opt,name=rtp_duplicated_counter,json=rtpDuplicatedCounter,proto3" json:"rtp_duplicated_counter,omitempty"`
	// Codec
	Codecname string `protobuf:"bytes,6,opt,name=codecname,proto3" json:"codecname,omitempty"`
	// Start & finish UNIX timestamp (milliseconds) of THIS report's window:
	//   - interval (chunk) report  -> [start_timestamp, finish_timestamp] is the chunk
	//   - final report (StreamFinish.report) -> covers the whole stream
	//
	// The window duration is finish_timestamp - start_timestamp; there is no
	// separate duration field (it was always derivable from these two).
	StartTimestamp  uint64 `protobuf:"varint,7,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	FinishTimestamp uint64 `protobuf:"varint,8,opt,name=finish_timestamp,json=finishTimestamp,proto3" json:"finish_timestamp,omitempty"`
	// Stream start UNIX timestamp (milliseconds): the time of the first media
	// packet of the whole stream. Constant across every interval report for a
	// given stream (unlike start_timestamp, which advances per chunk). For the
	// final report it equals start_timestamp.
	StartTimestampStream uint64 `protobuf:"varint,20,opt,name=start_timestamp_stream,json=startTimestampStream,proto3" json:"start_timestamp_stream,omitempty"`
	// Duration of decoded audio
	DurationAudio float32 `protobuf:"fixed32,9,opt,name=duration_audio,json=durationAudio,proto3" json:"duration_audio,omitempty"`
	// Can be path to decoded audio file
	UserData string `protobuf:"bytes,10,opt,name=user_data,json=userData,proto3" json:"user_data,omitempty"`
	// Sevana R-factor
	SevanaRfactor float32 `protobuf:"fixed32,11,opt,name=sevana_rfactor,json=sevanaRfactor,proto3" json:"sevana_rfactor,omitempty"`
	// CSV interval report
	IntervalReport string             `protobuf:"bytes,12,opt,name=interval_report,json=intervalReport,proto3" json:"interval_report,omitempty"`
	Sip            *Stream_SipInfo    `protobuf:"bytes,13,opt,name=sip,proto3" json:"sip,omitempty"`
	Echolist       []*Stream_EchoPeak `protobuf:"bytes,14,rep,name=echolist,proto3" json:"echolist,omitempty"`
	DtxInfo        *Stream_DtxInfo    `protobuf:"bytes,15,opt,name=dtx_info,json=dtxInfo,proto3" json:"dtx_info,omitempty"`
	// Aggregated metrics (min/max/avg/current). Jitter and RTT are expressed in
	// milliseconds; the two MOS scores are on the usual 1..5 scale.
	Jitter        *MetricStats `protobuf:"bytes,16,opt,name=jitter,proto3" json:"jitter,omitempty"`
	Rtt           *MetricStats `protobuf:"bytes,17,opt,name=rtt,proto3" json:"rtt,omitempty"`
	MosNetwork    *MetricStats `protobuf:"bytes,18,opt,name=mos_network,json=mosNetwork,proto3" json:"mos_network,omitempty"`
	MosSevana     *MetricStats `protobuf:"bytes,19,opt,name=mos_sevana,json=mosSevana,proto3" json:"mos_sevana,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream) Reset() {
	*x = Stream{}
	mi := &file_capturemessage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream) ProtoMessage() {}

func (x *Stream) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream.ProtoReflect.Descriptor instead.
func (*Stream) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{5}
}

func (x *Stream) GetStreamId() *StreamId {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *Stream) GetRtpPacketCounter() uint64 {
	if x != nil {
		return x.RtpPacketCounter
	}
	return 0
}

func (x *Stream) GetRtpIllegalPacketCounter() uint64 {
	if x != nil {
		return x.RtpIllegalPacketCounter
	}
	return 0
}

func (x *Stream) GetRtpLostPacketCounter() uint64 {
	if x != nil {
		return x.RtpLostPacketCounter
	}
	return 0
}

func (x *Stream) GetRtpDuplicatedCounter() uint64 {
	if x != nil {
		return x.RtpDuplicatedCounter
	}
	return 0
}

func (x *Stream) GetCodecname() string {
	if x != nil {
		return x.Codecname
	}
	return ""
}

func (x *Stream) GetStartTimestamp() uint64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *Stream) GetFinishTimestamp() uint64 {
	if x != nil {
		return x.FinishTimestamp
	}
	return 0
}

func (x *Stream) GetStartTimestampStream() uint64 {
	if x != nil {
		return x.StartTimestampStream
	}
	return 0
}

func (x *Stream) GetDurationAudio() float32 {
	if x != nil {
		return x.DurationAudio
	}
	return 0
}

func (x *Stream) GetUserData() string {
	if x != nil {
		return x.UserData
	}
	return ""
}

func (x *Stream) GetSevanaRfactor() float32 {
	if x != nil {
		return x.SevanaRfactor
	}
	return 0
}

func (x *Stream) GetIntervalReport() string {
	if x != nil {
		return x.IntervalReport
	}
	return ""
}

func (x *Stream) GetSip() *Stream_SipInfo {
	if x != nil {
		return x.Sip
	}
	return nil
}

func (x *Stream) GetEcholist() []*Stream_EchoPeak {
	if x != nil {
		return x.Echolist
	}
	return nil
}

func (x *Stream) GetDtxInfo() *Stream_DtxInfo {
	if x != nil {
		return x.DtxInfo
	}
	return nil
}

func (x *Stream) GetJitter() *MetricStats {
	if x != nil {
		return x.Jitter
	}
	return nil
}

func (x *Stream) GetRtt() *MetricStats {
	if x != nil {
		return x.Rtt
	}
	return nil
}

func (x *Stream) GetMosNetwork() *MetricStats {
	if x != nil {
		return x.MosNetwork
	}
	return nil
}

func (x *Stream) GetMosSevana() *MetricStats {
	if x != nil {
		return x.MosSevana
	}
	return nil
}

type StreamStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      *StreamId              `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamStart) Reset() {
	*x = StreamStart{}
	mi := &file_capturemessage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStart) ProtoMessage() {}

func (x *StreamStart) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStart.ProtoReflect.Descriptor instead.
func (*StreamStart) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{6}
}

func (x *StreamStart) GetStreamId() *StreamId {
	if x != nil {
		return x.StreamId
	}
	return nil
}

type StreamFinish struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      *StreamId              `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Report        *Stream                `protobuf:"bytes,2,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamFinish) Reset() {
	*x = StreamFinish{}
	mi := &file_capturemessage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamFinish) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamFinish) ProtoMessage() {}

func (x *StreamFinish) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamFinish.ProtoReflect.Descriptor instead.
func (*StreamFinish) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{7}
}

func (x *StreamFinish) GetStreamId() *StreamId {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *StreamFinish) GetReport() *Stream {
	if x != nil {
		return x.Report
	}
	return nil
}

type StreamGhost struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	StreamId *StreamId              `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	// RTP packets seen for this flow before it was dropped as a ghost. A ghost
	// is a sub-threshold stream (count < RTP_STREAM_DETECT_LIMIT) that never
	// crossed into full reporting, so this is the total number of packets that
	// were ever detected for it.
	PacketCounter uint64 `protobuf:"varint,2,opt,name=packet_counter,json=packetCounter,proto3" json:"packet_counter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamGhost) Reset() {
	*x = StreamGhost{}
	mi := &file_capturemessage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamGhost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamGhost) ProtoMessage() {}

func (x *StreamGhost) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamGhost.ProtoReflect.Descriptor instead.
func (*StreamGhost) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{8}
}

func (x *StreamGhost) GetStreamId() *StreamId {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *StreamGhost) GetPacketCounter() uint64 {
	if x != nil {
		return x.PacketCounter
	}
	return 0
}

// Decoded audio for a stream, delivered in-band so subscribers do not need
// access to vq-core's filesystem. Emitted only when the "publish-audio" option
// is enabled; one message accompanies each interval/final Stream report that
// produced audio. The payload is a self-contained WAV file (canonical PCM16
// header + samples), so subscribers can save or play it without extra metadata.
type StreamAudio struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	StreamId        *StreamId              `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	Wav             []byte                 `protobuf:"bytes,2,opt,name=wav,proto3" json:"wav,omitempty"`                                                 // complete WAV (header + PCM16 mono)
	StartTimestamp  uint64                 `protobuf:"varint,3,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`    // UNIX timestamp (ms) of this chunk
	FinishTimestamp uint64                 `protobuf:"varint,4,opt,name=finish_timestamp,json=finishTimestamp,proto3" json:"finish_timestamp,omitempty"` // UNIX timestamp (ms) of this chunk
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StreamAudio) Reset() {
	*x = StreamAudio{}
	mi := &file_capturemessage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAudio) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAudio) ProtoMessage() {}

func (x *StreamAudio) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAudio.ProtoReflect.Descriptor instead.
func (*StreamAudio) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{9}
}

func (x *StreamAudio) GetStreamId() *StreamId {
	if x != nil {
		return x.StreamId
	}
	return nil
}

func (x *StreamAudio) GetWav() []byte {
	if x != nil {
		return x.Wav
	}
	return nil
}

func (x *StreamAudio) GetStartTimestamp() uint64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *StreamAudio) GetFinishTimestamp() uint64 {
	if x != nil {
		return x.FinishTimestamp
	}
	return 0
}

type InstanceStatistics struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ServerTime           string                 `protobuf:"bytes,3,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	PvqaInstanceCounter  uint64                 `protobuf:"varint,4,opt,name=pvqa_instance_counter,json=pvqaInstanceCounter,proto3" json:"pvqa_instance_counter,omitempty"`
	PvqaProcessedSeconds uint64                 `protobuf:"varint,5,opt,name=pvqa_processed_seconds,json=pvqaProcessedSeconds,proto3" json:"pvqa_processed_seconds,omitempty"`
	UptimeSeconds        uint64                 `protobuf:"varint,6,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Version              string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	ActiveDecoderCounter uint64                 `protobuf:"varint,8,opt,name=active_decoder_counter,json=activeDecoderCounter,proto3" json:"active_decoder_counter,omitempty"` // live StreamDecoder objects right now
	TotalDecoderCounter  uint64                 `protobuf:"varint,9,opt,name=total_decoder_counter,json=totalDecoderCounter,proto3" json:"total_decoder_counter,omitempty"`    // StreamDecoders created since startup
	// Streams currently doing audio decode + PVQA right now (subset of
	// active_decoder_counter). Reflects how full the audio set is — the SIP track
	// list and/or the count-based max-streams-audio cap. 0 when no stream is being
	// decoded (the network-MOS-only default).
	ActiveAudioDecoderCounter uint64          `protobuf:"varint,24,opt,name=active_audio_decoder_counter,json=activeAudioDecoderCounter,proto3" json:"active_audio_decoder_counter,omitempty"`
	Capturers                 []*CaptureStats `protobuf:"bytes,10,rep,name=capturers,proto3" json:"capturers,omitempty"`
	// Live SipManager Call objects right now. Grows with call volume and only
	// shrinks as calls are garbage-collected; a value that keeps climbing while
	// active_decoder_counter stays flat indicates Call objects are not being
	// released (e.g. calls that never received a BYE).
	SipCallCounter uint64 `protobuf:"varint,11,opt,name=sip_call_counter,json=sipCallCounter,proto3" json:"sip_call_counter,omitempty"`
	// Live reSIProcate object counts (leak indicators). resip_message_counter
	// covers every resip::Message-derived object; resip_sip_message_counter is
	// the SIP-specific subset. A value that keeps climbing flags leaked parsed
	// messages (e.g. at the SipManager clone() sites).
	ResipMessageCounter    uint64 `protobuf:"varint,12,opt,name=resip_message_counter,json=resipMessageCounter,proto3" json:"resip_message_counter,omitempty"`
	ResipSipMessageCounter uint64 `protobuf:"varint,13,opt,name=resip_sip_message_counter,json=resipSipMessageCounter,proto3" json:"resip_sip_message_counter,omitempty"`
	// Allocator (tcmalloc) memory figures, 0 when not built against tcmalloc.
	// mem_allocated_bytes is live application usage; mem_heap_size is total
	// mapped from the OS; mem_pageheap_free_bytes is free-but-mapped memory the
	// allocator retains (the reclaimable gap that explains high RSS without a
	// leak). RSS is roughly mem_heap_size minus what has been returned to the OS.
	MemAllocatedBytes    uint64 `protobuf:"varint,14,opt,name=mem_allocated_bytes,json=memAllocatedBytes,proto3" json:"mem_allocated_bytes,omitempty"`
	MemHeapSize          uint64 `protobuf:"varint,15,opt,name=mem_heap_size,json=memHeapSize,proto3" json:"mem_heap_size,omitempty"`
	MemPageheapFreeBytes uint64 `protobuf:"varint,16,opt,name=mem_pageheap_free_bytes,json=memPageheapFreeBytes,proto3" json:"mem_pageheap_free_bytes,omitempty"`
	// Allocator load (tcmalloc malloc/free hooks). mem_alloc_count /
	// mem_free_count are cumulative since startup; mem_allocs_per_sec /
	// mem_frees_per_sec are the per-second rates over the last report interval.
	// All 0 unless allocation tracking is enabled (track-allocations) on a
	// tcmalloc build. High allocs/sec with allocs ~= frees is healthy churn;
	// a persistent allocs > frees gap is the live-object growth that drives RSS.
	MemAllocCount   uint64  `protobuf:"varint,17,opt,name=mem_alloc_count,json=memAllocCount,proto3" json:"mem_alloc_count,omitempty"`
	MemFreeCount    uint64  `protobuf:"varint,18,opt,name=mem_free_count,json=memFreeCount,proto3" json:"mem_free_count,omitempty"`
	MemAllocsPerSec float64 `protobuf:"fixed64,19,opt,name=mem_allocs_per_sec,json=memAllocsPerSec,proto3" json:"mem_allocs_per_sec,omitempty"`
	MemFreesPerSec  float64 `protobuf:"fixed64,20,opt,name=mem_frees_per_sec,json=memFreesPerSec,proto3" json:"mem_frees_per_sec,omitempty"`
	// Process CPU usage (whole process, all threads), from getrusage(RUSAGE_SELF).
	// cpu_user_seconds / cpu_system_seconds are cumulative CPU time consumed since
	// startup (user space vs kernel on the process's behalf). cpu_usage_percent is
	// the busy fraction over the last report interval expressed top-style as a
	// percentage of a SINGLE core, so it can exceed 100 on a multithreaded load
	// (e.g. 350 means ~3.5 cores busy). Divide by the core count for a 0-100
	// machine-wide figure. 0 on the first report (no prior interval to diff).
	CpuUserSeconds   float64 `protobuf:"fixed64,21,opt,name=cpu_user_seconds,json=cpuUserSeconds,proto3" json:"cpu_user_seconds,omitempty"`
	CpuSystemSeconds float64 `protobuf:"fixed64,22,opt,name=cpu_system_seconds,json=cpuSystemSeconds,proto3" json:"cpu_system_seconds,omitempty"`
	CpuUsagePercent  float64 `protobuf:"fixed64,23,opt,name=cpu_usage_percent,json=cpuUsagePercent,proto3" json:"cpu_usage_percent,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *InstanceStatistics) Reset() {
	*x = InstanceStatistics{}
	mi := &file_capturemessage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceStatistics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceStatistics) ProtoMessage() {}

func (x *InstanceStatistics) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceStatistics.ProtoReflect.Descriptor instead.
func (*InstanceStatistics) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{10}
}

func (x *InstanceStatistics) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InstanceStatistics) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InstanceStatistics) GetServerTime() string {
	if x != nil {
		return x.ServerTime
	}
	return ""
}

func (x *InstanceStatistics) GetPvqaInstanceCounter() uint64 {
	if x != nil {
		return x.PvqaInstanceCounter
	}
	return 0
}

func (x *InstanceStatistics) GetPvqaProcessedSeconds() uint64 {
	if x != nil {
		return x.PvqaProcessedSeconds
	}
	return 0
}

func (x *InstanceStatistics) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *InstanceStatistics) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InstanceStatistics) GetActiveDecoderCounter() uint64 {
	if x != nil {
		return x.ActiveDecoderCounter
	}
	return 0
}

func (x *InstanceStatistics) GetTotalDecoderCounter() uint64 {
	if x != nil {
		return x.TotalDecoderCounter
	}
	return 0
}

func (x *InstanceStatistics) GetActiveAudioDecoderCounter() uint64 {
	if x != nil {
		return x.ActiveAudioDecoderCounter
	}
	return 0
}

func (x *InstanceStatistics) GetCapturers() []*CaptureStats {
	if x != nil {
		return x.Capturers
	}
	return nil
}

func (x *InstanceStatistics) GetSipCallCounter() uint64 {
	if x != nil {
		return x.SipCallCounter
	}
	return 0
}

func (x *InstanceStatistics) GetResipMessageCounter() uint64 {
	if x != nil {
		return x.ResipMessageCounter
	}
	return 0
}

func (x *InstanceStatistics) GetResipSipMessageCounter() uint64 {
	if x != nil {
		return x.ResipSipMessageCounter
	}
	return 0
}

func (x *InstanceStatistics) GetMemAllocatedBytes() uint64 {
	if x != nil {
		return x.MemAllocatedBytes
	}
	return 0
}

func (x *InstanceStatistics) GetMemHeapSize() uint64 {
	if x != nil {
		return x.MemHeapSize
	}
	return 0
}

func (x *InstanceStatistics) GetMemPageheapFreeBytes() uint64 {
	if x != nil {
		return x.MemPageheapFreeBytes
	}
	return 0
}

func (x *InstanceStatistics) GetMemAllocCount() uint64 {
	if x != nil {
		return x.MemAllocCount
	}
	return 0
}

func (x *InstanceStatistics) GetMemFreeCount() uint64 {
	if x != nil {
		return x.MemFreeCount
	}
	return 0
}

func (x *InstanceStatistics) GetMemAllocsPerSec() float64 {
	if x != nil {
		return x.MemAllocsPerSec
	}
	return 0
}

func (x *InstanceStatistics) GetMemFreesPerSec() float64 {
	if x != nil {
		return x.MemFreesPerSec
	}
	return 0
}

func (x *InstanceStatistics) GetCpuUserSeconds() float64 {
	if x != nil {
		return x.CpuUserSeconds
	}
	return 0
}

func (x *InstanceStatistics) GetCpuSystemSeconds() float64 {
	if x != nil {
		return x.CpuSystemSeconds
	}
	return 0
}

func (x *InstanceStatistics) GetCpuUsagePercent() float64 {
	if x != nil {
		return x.CpuUsagePercent
	}
	return 0
}

// One party of a SIP dialog, as seen in signalling (maps to SipManager::Call::Peer).
type SipPeer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aor           string                 `protobuf:"bytes,1,opt,name=aor,proto3" json:"aor,omitempty"`                                       // From/To AOR, e.g. sip:alice@example.com
	UserAgent     string                 `protobuf:"bytes,2,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`          // User-Agent / Server header if present
	RtpAddresses  []*IpAddress           `protobuf:"bytes,3,rep,name=rtp_addresses,json=rtpAddresses,proto3" json:"rtp_addresses,omitempty"` // media addresses advertised in SDP (c=/m=)
	Codecs        string                 `protobuf:"bytes,4,opt,name=codecs,proto3" json:"codecs,omitempty"`                                 // resolved codec settings, one line (cf. Stream.codecname)
	Ssrc          uint32                 `protobuf:"varint,5,opt,name=ssrc,proto3" json:"ssrc,omitempty"`                                    // SSRC this peer is expected to send (0 if unknown)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SipPeer) Reset() {
	*x = SipPeer{}
	mi := &file_capturemessage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SipPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SipPeer) ProtoMessage() {}

func (x *SipPeer) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SipPeer.ProtoReflect.Descriptor instead.
func (*SipPeer) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{11}
}

func (x *SipPeer) GetAor() string {
	if x != nil {
		return x.Aor
	}
	return ""
}

func (x *SipPeer) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *SipPeer) GetRtpAddresses() []*IpAddress {
	if x != nil {
		return x.RtpAddresses
	}
	return nil
}

func (x *SipPeer) GetCodecs() string {
	if x != nil {
		return x.Codecs
	}
	return ""
}

func (x *SipPeer) GetSsrc() uint32 {
	if x != nil {
		return x.Ssrc
	}
	return 0
}

// SIP call start — emitted once the call is established (setup response seen).
type SipCallStart struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CallId          string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`                             // SIP Call-ID
	Timestamp       uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                    // establishment time, UNIX timestamp (ms) = mSetupTime
	Caller          *SipPeer               `protobuf:"bytes,3,opt,name=caller,proto3" json:"caller,omitempty"`                                           // mPeers.first  (originator)
	Callee          *SipPeer               `protobuf:"bytes,4,opt,name=callee,proto3" json:"callee,omitempty"`                                           // mPeers.second (answerer)
	SetupCode       uint32                 `protobuf:"varint,5,opt,name=setup_code,json=setupCode,proto3" json:"setup_code,omitempty"`                   // response code that established the call (default 200)
	InviteTimestamp uint64                 `protobuf:"varint,6,opt,name=invite_timestamp,json=inviteTimestamp,proto3" json:"invite_timestamp,omitempty"` // first INVITE observed, UNIX timestamp (ms) — for post-dial delay
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SipCallStart) Reset() {
	*x = SipCallStart{}
	mi := &file_capturemessage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SipCallStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SipCallStart) ProtoMessage() {}

func (x *SipCallStart) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SipCallStart.ProtoReflect.Descriptor instead.
func (*SipCallStart) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{12}
}

func (x *SipCallStart) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *SipCallStart) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SipCallStart) GetCaller() *SipPeer {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *SipCallStart) GetCallee() *SipPeer {
	if x != nil {
		return x.Callee
	}
	return nil
}

func (x *SipCallStart) GetSetupCode() uint32 {
	if x != nil {
		return x.SetupCode
	}
	return 0
}

func (x *SipCallStart) GetInviteTimestamp() uint64 {
	if x != nil {
		return x.InviteTimestamp
	}
	return 0
}

// SIP call end — emitted on BYE.
type SipCallEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                                      // BYE time (mByeTime), UNIX timestamp (ms)
	ByeDirection  SipDirection           `protobuf:"varint,3,opt,name=bye_direction,json=byeDirection,proto3,enum=messages.SipDirection" json:"bye_direction,omitempty"` // who sent the BYE
	ResponseCodes []uint32               `protobuf:"varint,4,rep,packed,name=response_codes,json=responseCodes,proto3" json:"response_codes,omitempty"`                  // response codes seen over the dialog (mResponseCodes)
	Duration      uint64                 `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`                                                        // milliseconds, mByeTime - mSetupTime (if both known)
	HasBye        bool                   `protobuf:"varint,6,opt,name=has_bye,json=hasBye,proto3" json:"has_bye,omitempty"`                                              // false => ended by timeout / dangling, not BYE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SipCallEnd) Reset() {
	*x = SipCallEnd{}
	mi := &file_capturemessage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SipCallEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SipCallEnd) ProtoMessage() {}

func (x *SipCallEnd) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SipCallEnd.ProtoReflect.Descriptor instead.
func (*SipCallEnd) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{13}
}

func (x *SipCallEnd) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *SipCallEnd) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SipCallEnd) GetByeDirection() SipDirection {
	if x != nil {
		return x.ByeDirection
	}
	return SipDirection_SIP_DIR_UNKNOWN
}

func (x *SipCallEnd) GetResponseCodes() []uint32 {
	if x != nil {
		return x.ResponseCodes
	}
	return nil
}

func (x *SipCallEnd) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *SipCallEnd) GetHasBye() bool {
	if x != nil {
		return x.HasBye
	}
	return false
}

// reINVITE (also covers UPDATE — same code path).
type SipReinvite struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                  // Reinvite::mTimestamp, UNIX timestamp (ms)
	IsRequest     bool                   `protobuf:"varint,3,opt,name=is_request,json=isRequest,proto3" json:"is_request,omitempty"` // request vs response (Reinvite::mIsRequest)
	Direction     SipDirection           `protobuf:"varint,4,opt,name=direction,proto3,enum=messages.SipDirection" json:"direction,omitempty"`
	UpdatedPeer   *SipPeer               `protobuf:"bytes,5,opt,name=updated_peer,json=updatedPeer,proto3" json:"updated_peer,omitempty"` // the peer whose SDP/media was renegotiated
	RawMessage    string                 `protobuf:"bytes,6,opt,name=raw_message,json=rawMessage,proto3" json:"raw_message,omitempty"`    // optional raw SIP text (Reinvite::mText)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SipReinvite) Reset() {
	*x = SipReinvite{}
	mi := &file_capturemessage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SipReinvite) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SipReinvite) ProtoMessage() {}

func (x *SipReinvite) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SipReinvite.ProtoReflect.Descriptor instead.
func (*SipReinvite) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{14}
}

func (x *SipReinvite) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *SipReinvite) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SipReinvite) GetIsRequest() bool {
	if x != nil {
		return x.IsRequest
	}
	return false
}

func (x *SipReinvite) GetDirection() SipDirection {
	if x != nil {
		return x.Direction
	}
	return SipDirection_SIP_DIR_UNKNOWN
}

func (x *SipReinvite) GetUpdatedPeer() *SipPeer {
	if x != nil {
		return x.UpdatedPeer
	}
	return nil
}

func (x *SipReinvite) GetRawMessage() string {
	if x != nil {
		return x.RawMessage
	}
	return ""
}

// SIP call attempt failed — emitted when an INVITE never reaches the setup code.
// Mutually exclusive with SipCallStart for a given Call-ID.
type SipCallFailed struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CallId          string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`                             // SIP Call-ID
	Timestamp       uint64                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                    // when failure was determined, UNIX timestamp (ms)
	Caller          *SipPeer               `protobuf:"bytes,3,opt,name=caller,proto3" json:"caller,omitempty"`                                           // mPeers.first  (originator)
	Callee          *SipPeer               `protobuf:"bytes,4,opt,name=callee,proto3" json:"callee,omitempty"`                                           // mPeers.second (answerer)
	InviteTimestamp uint64                 `protobuf:"varint,5,opt,name=invite_timestamp,json=inviteTimestamp,proto3" json:"invite_timestamp,omitempty"` // first INVITE observed, UNIX timestamp (ms)
	Reason          SipCallFailed_Reason   `protobuf:"varint,6,opt,name=reason,proto3,enum=messages.SipCallFailed_Reason" json:"reason,omitempty"`
	ResponseCode    uint32                 `protobuf:"varint,7,opt,name=response_code,json=responseCode,proto3" json:"response_code,omitempty"` // final SIP response code (e.g. 486, 603); 0 if none
	ReasonPhrase    string                 `protobuf:"bytes,8,opt,name=reason_phrase,json=reasonPhrase,proto3" json:"reason_phrase,omitempty"`  // optional reason phrase from the status line
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SipCallFailed) Reset() {
	*x = SipCallFailed{}
	mi := &file_capturemessage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SipCallFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SipCallFailed) ProtoMessage() {}

func (x *SipCallFailed) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SipCallFailed.ProtoReflect.Descriptor instead.
func (*SipCallFailed) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{15}
}

func (x *SipCallFailed) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *SipCallFailed) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SipCallFailed) GetCaller() *SipPeer {
	if x != nil {
		return x.Caller
	}
	return nil
}

func (x *SipCallFailed) GetCallee() *SipPeer {
	if x != nil {
		return x.Callee
	}
	return nil
}

func (x *SipCallFailed) GetInviteTimestamp() uint64 {
	if x != nil {
		return x.InviteTimestamp
	}
	return 0
}

func (x *SipCallFailed) GetReason() SipCallFailed_Reason {
	if x != nil {
		return x.Reason
	}
	return SipCallFailed_REASON_UNKNOWN
}

func (x *SipCallFailed) GetResponseCode() uint32 {
	if x != nil {
		return x.ResponseCode
	}
	return 0
}

func (x *SipCallFailed) GetReasonPhrase() string {
	if x != nil {
		return x.ReasonPhrase
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamReport  *Stream                `protobuf:"bytes,1,opt,name=stream_report,json=streamReport,proto3" json:"stream_report,omitempty"`
	StreamStart   *StreamStart           `protobuf:"bytes,2,opt,name=stream_start,json=streamStart,proto3" json:"stream_start,omitempty"`
	StreamFinish  *StreamFinish          `protobuf:"bytes,3,opt,name=stream_finish,json=streamFinish,proto3" json:"stream_finish,omitempty"`
	CaptureStats  *CaptureStats          `protobuf:"bytes,4,opt,name=capture_stats,json=captureStats,proto3" json:"capture_stats,omitempty"`
	StreamGhost   *StreamGhost           `protobuf:"bytes,5,opt,name=stream_ghost,json=streamGhost,proto3" json:"stream_ghost,omitempty"`
	InstanceStats *InstanceStatistics    `protobuf:"bytes,6,opt,name=instance_stats,json=instanceStats,proto3" json:"instance_stats,omitempty"`
	SipCallStart  *SipCallStart          `protobuf:"bytes,7,opt,name=sip_call_start,json=sipCallStart,proto3" json:"sip_call_start,omitempty"`
	SipCallEnd    *SipCallEnd            `protobuf:"bytes,8,opt,name=sip_call_end,json=sipCallEnd,proto3" json:"sip_call_end,omitempty"`
	SipReinvite   *SipReinvite           `protobuf:"bytes,9,opt,name=sip_reinvite,json=sipReinvite,proto3" json:"sip_reinvite,omitempty"`
	SipCallFailed *SipCallFailed         `protobuf:"bytes,10,opt,name=sip_call_failed,json=sipCallFailed,proto3" json:"sip_call_failed,omitempty"`
	StreamAudio   *StreamAudio           `protobuf:"bytes,11,opt,name=stream_audio,json=streamAudio,proto3" json:"stream_audio,omitempty"`
	EspSaEvent    *EspSaEvent            `protobuf:"bytes,12,opt,name=esp_sa_event,json=espSaEvent,proto3" json:"esp_sa_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_capturemessage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{16}
}

func (x *Event) GetStreamReport() *Stream {
	if x != nil {
		return x.StreamReport
	}
	return nil
}

func (x *Event) GetStreamStart() *StreamStart {
	if x != nil {
		return x.StreamStart
	}
	return nil
}

func (x *Event) GetStreamFinish() *StreamFinish {
	if x != nil {
		return x.StreamFinish
	}
	return nil
}

func (x *Event) GetCaptureStats() *CaptureStats {
	if x != nil {
		return x.CaptureStats
	}
	return nil
}

func (x *Event) GetStreamGhost() *StreamGhost {
	if x != nil {
		return x.StreamGhost
	}
	return nil
}

func (x *Event) GetInstanceStats() *InstanceStatistics {
	if x != nil {
		return x.InstanceStats
	}
	return nil
}

func (x *Event) GetSipCallStart() *SipCallStart {
	if x != nil {
		return x.SipCallStart
	}
	return nil
}

func (x *Event) GetSipCallEnd() *SipCallEnd {
	if x != nil {
		return x.SipCallEnd
	}
	return nil
}

func (x *Event) GetSipReinvite() *SipReinvite {
	if x != nil {
		return x.SipReinvite
	}
	return nil
}

func (x *Event) GetSipCallFailed() *SipCallFailed {
	if x != nil {
		return x.SipCallFailed
	}
	return nil
}

func (x *Event) GetStreamAudio() *StreamAudio {
	if x != nil {
		return x.StreamAudio
	}
	return nil
}

func (x *Event) GetEspSaEvent() *EspSaEvent {
	if x != nil {
		return x.EspSaEvent
	}
	return nil
}

// One entry of the track list. The pattern is matched case-insensitively as a
// substring against both peers' SIP AOR (e.g. "alice", "sip:alice@host").
type TrackEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SipPattern    string                 `protobuf:"bytes,1,opt,name=sip_pattern,json=sipPattern,proto3" json:"sip_pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEntry) Reset() {
	*x = TrackEntry{}
	mi := &file_capturemessage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEntry) ProtoMessage() {}

func (x *TrackEntry) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEntry.ProtoReflect.Descriptor instead.
func (*TrackEntry) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{17}
}

func (x *TrackEntry) GetSipPattern() string {
	if x != nil {
		return x.SipPattern
	}
	return ""
}

// Control request sent to vq-core.
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            Command_Op             `protobuf:"varint,1,opt,name=op,proto3,enum=messages.Command_Op" json:"op,omitempty"`
	Entries       []*TrackEntry          `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"` // ignored / empty for TRACK_QUERY
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_capturemessage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{18}
}

func (x *Command) GetOp() Command_Op {
	if x != nil {
		return x.Op
	}
	return Command_TRACK_ADD
}

func (x *Command) GetEntries() []*TrackEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Reply to a Command. Exactly one is sent per Command (ZMQ_REP contract).
type CommandAck struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Ok              bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                                                  // false => command rejected
	Error           string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`                                             // human-readable reason when !ok
	Current         []*TrackEntry          `protobuf:"bytes,3,rep,name=current,proto3" json:"current,omitempty"`                                         // full list after the op (or for QUERY)
	AffectedStreams uint32                 `protobuf:"varint,4,opt,name=affected_streams,json=affectedStreams,proto3" json:"affected_streams,omitempty"` // live streams that began decoding as a result
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommandAck) Reset() {
	*x = CommandAck{}
	mi := &file_capturemessage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAck) ProtoMessage() {}

func (x *CommandAck) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAck.ProtoReflect.Descriptor instead.
func (*CommandAck) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{19}
}

func (x *CommandAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommandAck) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CommandAck) GetCurrent() []*TrackEntry {
	if x != nil {
		return x.Current
	}
	return nil
}

func (x *CommandAck) GetAffectedStreams() uint32 {
	if x != nil {
		return x.AffectedStreams
	}
	return 0
}

// SIP correlation for the stream, unset if the call was not seen on SIP.
type Stream_SipInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CallId        string                 `protobuf:"bytes,1,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"` // SIP Call-ID
	Peer1         string                 `protobuf:"bytes,2,opt,name=peer1,proto3" json:"peer1,omitempty"`                 // first party AOR  (QualityReport mSip.mPeerA)
	Peer2         string                 `protobuf:"bytes,3,opt,name=peer2,proto3" json:"peer2,omitempty"`                 // second party AOR (QualityReport mSip.mPeerB)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream_SipInfo) Reset() {
	*x = Stream_SipInfo{}
	mi := &file_capturemessage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream_SipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream_SipInfo) ProtoMessage() {}

func (x *Stream_SipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream_SipInfo.ProtoReflect.Descriptor instead.
func (*Stream_SipInfo) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Stream_SipInfo) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

func (x *Stream_SipInfo) GetPeer1() string {
	if x != nil {
		return x.Peer1
	}
	return ""
}

func (x *Stream_SipInfo) GetPeer2() string {
	if x != nil {
		return x.Peer2
	}
	return ""
}

type Stream_EchoPeak struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          float32                `protobuf:"fixed32,1,opt,name=time,proto3" json:"time,omitempty"`
	Level         float32                `protobuf:"fixed32,2,opt,name=level,proto3" json:"level,omitempty"`
	Length        float32                `protobuf:"fixed32,3,opt,name=length,proto3" json:"length,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream_EchoPeak) Reset() {
	*x = Stream_EchoPeak{}
	mi := &file_capturemessage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream_EchoPeak) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream_EchoPeak) ProtoMessage() {}

func (x *Stream_EchoPeak) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream_EchoPeak.ProtoReflect.Descriptor instead.
func (*Stream_EchoPeak) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{5, 1}
}

func (x *Stream_EchoPeak) GetTime() float32 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Stream_EchoPeak) GetLevel() float32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Stream_EchoPeak) GetLength() float32 {
	if x != nil {
		return x.Length
	}
	return 0
}

// AMR-NB/WB and EVS frame statistics, derived from the RTP payload header
// without decoding. Populated even for network-MOS-only streams; stays at
// proto3 defaults (unset) for SRTP and non-AMR/EVS codecs.
type Stream_DtxInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountSid      uint64                 `protobuf:"varint,1,opt,name=count_sid,json=countSid,proto3" json:"count_sid,omitempty"`       // SID / comfort-noise frames
	CountDtx      uint64                 `protobuf:"varint,2,opt,name=count_dtx,json=countDtx,proto3" json:"count_dtx,omitempty"`       // NO_DATA frames (DTX silence, nothing sent)
	CountTotal    uint64                 `protobuf:"varint,3,opt,name=count_total,json=countTotal,proto3" json:"count_total,omitempty"` // total AMR/EVS frames inspected (any class)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stream_DtxInfo) Reset() {
	*x = Stream_DtxInfo{}
	mi := &file_capturemessage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stream_DtxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stream_DtxInfo) ProtoMessage() {}

func (x *Stream_DtxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_capturemessage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stream_DtxInfo.ProtoReflect.Descriptor instead.
func (*Stream_DtxInfo) Descriptor() ([]byte, []int) {
	return file_capturemessage_proto_rawDescGZIP(), []int{5, 2}
}

func (x *Stream_DtxInfo) GetCountSid() uint64 {
	if x != nil {
		return x.CountSid
	}
	return 0
}

func (x *Stream_DtxInfo) GetCountDtx() uint64 {
	if x != nil {
		return x.CountDtx
	}
	return 0
}

func (x *Stream_DtxInfo) GetCountTotal() uint64 {
	if x != nil {
		return x.CountTotal
	}
	return 0
}

var File_capturemessage_proto protoreflect.FileDescriptor

const file_capturemessage_proto_rawDesc = "" +
	"\n" +
	"\x14capturemessage.proto\x12\bmessages\"\x9b\x01\n" +
	"\tIpAddress\x122\n" +
	"\x06family\x18\x01 \x01(\x0e2\x1a.messages.IpAddress.FamilyR\x06family\x12\x18\n" +
	"\arelayed\x18\x02 \x01(\bR\arelayed\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\fR\x02ip\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\"\x1c\n" +
	"\x06Family\x12\b\n" +
	"\x04IPv4\x10\x00\x12\b\n" +
	"\x04IPv6\x10\x01\"\xc7\x01\n" +
	"\n" +
	"EspSaEvent\x12\x12\n" +
	"\x04spis\x18\x01 \x03(\rR\x04spis\x12%\n" +
	"\x03dst\x18\x02 \x01(\v2\x13.messages.IpAddressR\x03dst\x12\x17\n" +
	"\aenc_alg\x18\x03 \x01(\tR\x06encAlg\x12\x19\n" +
	"\bauth_alg\x18\x04 \x01(\tR\aauthAlg\x12\x16\n" +
	"\x06source\x18\x05 \x01(\rR\x06source\x12\x17\n" +
	"\aenc_key\x18\x06 \x01(\fR\x06encKey\x12\x19\n" +
	"\bauth_key\x18\a \x01(\fR\aauthKey\"\x80\x01\n" +
	"\bStreamId\x12%\n" +
	"\x03src\x18\x01 \x01(\v2\x13.messages.IpAddressR\x03src\x12%\n" +
	"\x03dst\x18\x02 \x01(\v2\x13.messages.IpAddressR\x03dst\x12\x12\n" +
	"\x04ssrc\x18\x03 \x01(\rR\x04ssrc\x12\x12\n" +
	"\x04uuid\x18\x04 \x01(\tR\x04uuid\"]\n" +
	"\vMetricStats\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x02R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x02R\x03max\x12\x10\n" +
	"\x03avg\x18\x03 \x01(\x02R\x03avg\x12\x18\n" +
	"\acurrent\x18\x04 \x01(\x02R\acurrent\"\xea\x03\n" +
	"\fCaptureStats\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x120\n" +
	"\x14total_packet_counter\x18\x02 \x01(\x04R\x12totalPacketCounter\x12,\n" +
	"\x12rtp_packet_counter\x18\x03 \x01(\x04R\x10rtpPacketCounter\x12,\n" +
	"\x12sip_packet_counter\x18\x04 \x01(\x04R\x10sipPacketCounter\x128\n" +
	"\x18truncated_packet_counter\x18\x05 \x01(\x04R\x16truncatedPacketCounter\x12$\n" +
	"\x0esrc_port_range\x18\x06 \x01(\tR\fsrcPortRange\x12$\n" +
	"\x0edst_port_range\x18\a \x01(\tR\fdstPortRange\x129\n" +
	"\x19dropped_hw_packet_counter\x18\b \x01(\x04R\x16droppedHwPacketCounter\x128\n" +
	"\x18erroneous_packet_counter\x18\t \x01(\x04R\x16erroneousPacketCounter\x129\n" +
	"\x19mbuf_alloc_failed_counter\x18\n" +
	" \x01(\x04R\x16mbufAllocFailedCounter\"\xaf\t\n" +
	"\x06Stream\x12/\n" +
	"\tstream_id\x18\x01 \x01(\v2\x12.messages.StreamIdR\bstreamId\x12,\n" +
	"\x12rtp_packet_counter\x18\x02 \x01(\x04R\x10rtpPacketCounter\x12;\n" +
	"\x1artp_illegal_packet_counter\x18\x03 \x01(\x04R\x17rtpIllegalPacketCounter\x125\n" +
	"\x17rtp_lost_packet_counter\x18\x04 \x01(\x04R\x14rtpLostPacketCounter\x124\n" +
	"\x16rtp_duplicated_counter\x18\x05 \x01(\x04R\x14rtpDuplicatedCounter\x12\x1c\n" +
	"\tcodecname\x18\x06 \x01(\tR\tcodecname\x12'\n" +
	"\x0fstart_timestamp\x18\a \x01(\x04R\x0estartTimestamp\x12)\n" +
	"\x10finish_timestamp\x18\b \x01(\x04R\x0ffinishTimestamp\x124\n" +
	"\x16start_timestamp_stream\x18\x14 \x01(\x04R\x14startTimestampStream\x12%\n" +
	"\x0eduration_audio\x18\t \x01(\x02R\rdurationAudio\x12\x1b\n" +
	"\tuser_data\x18\n" +
	" \x01(\tR\buserData\x12%\n" +
	"\x0esevana_rfactor\x18\v \x01(\x02R\rsevanaRfactor\x12'\n" +
	"\x0finterval_report\x18\f \x01(\tR\x0eintervalReport\x12*\n" +
	"\x03sip\x18\r \x01(\v2\x18.messages.Stream.SipInfoR\x03sip\x125\n" +
	"\becholist\x18\x0e \x03(\v2\x19.messages.Stream.EchoPeakR\becholist\x123\n" +
	"\bdtx_info\x18\x0f \x01(\v2\x18.messages.Stream.DtxInfoR\adtxInfo\x12-\n" +
	"\x06jitter\x18\x10 \x01(\v2\x15.messages.MetricStatsR\x06jitter\x12'\n" +
	"\x03rtt\x18\x11 \x01(\v2\x15.messages.MetricStatsR\x03rtt\x126\n" +
	"\vmos_network\x18\x12 \x01(\v2\x15.messages.MetricStatsR\n" +
	"mosNetwork\x124\n" +
	"\n" +
	"mos_sevana\x18\x13 \x01(\v2\x15.messages.MetricStatsR\tmosSevana\x1aN\n" +
	"\aSipInfo\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x14\n" +
	"\x05peer1\x18\x02 \x01(\tR\x05peer1\x12\x14\n" +
	"\x05peer2\x18\x03 \x01(\tR\x05peer2\x1aL\n" +
	"\bEchoPeak\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x02R\x04time\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x02R\x05level\x12\x16\n" +
	"\x06length\x18\x03 \x01(\x02R\x06length\x1ad\n" +
	"\aDtxInfo\x12\x1b\n" +
	"\tcount_sid\x18\x01 \x01(\x04R\bcountSid\x12\x1b\n" +
	"\tcount_dtx\x18\x02 \x01(\x04R\bcountDtx\x12\x1f\n" +
	"\vcount_total\x18\x03 \x01(\x04R\n" +
	"countTotal\">\n" +
	"\vStreamStart\x12/\n" +
	"\tstream_id\x18\x01 \x01(\v2\x12.messages.StreamIdR\bstreamId\"i\n" +
	"\fStreamFinish\x12/\n" +
	"\tstream_id\x18\x01 \x01(\v2\x12.messages.StreamIdR\bstreamId\x12(\n" +
	"\x06report\x18\x02 \x01(\v2\x10.messages.StreamR\x06report\"e\n" +
	"\vStreamGhost\x12/\n" +
	"\tstream_id\x18\x01 \x01(\v2\x12.messages.StreamIdR\bstreamId\x12%\n" +
	"\x0epacket_counter\x18\x02 \x01(\x04R\rpacketCounter\"\xa4\x01\n" +
	"\vStreamAudio\x12/\n" +
	"\tstream_id\x18\x01 \x01(\v2\x12.messages.StreamIdR\bstreamId\x12\x10\n" +
	"\x03wav\x18\x02 \x01(\fR\x03wav\x12'\n" +
	"\x0fstart_timestamp\x18\x03 \x01(\x04R\x0estartTimestamp\x12)\n" +
	"\x10finish_timestamp\x18\x04 \x01(\x04R\x0ffinishTimestamp\"\xb3\b\n" +
	"\x12InstanceStatistics\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vserver_time\x18\x03 \x01(\tR\n" +
	"serverTime\x122\n" +
	"\x15pvqa_instance_counter\x18\x04 \x01(\x04R\x13pvqaInstanceCounter\x124\n" +
	"\x16pvqa_processed_seconds\x18\x05 \x01(\x04R\x14pvqaProcessedSeconds\x12%\n" +
	"\x0euptime_seconds\x18\x06 \x01(\x04R\ruptimeSeconds\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x124\n" +
	"\x16active_decoder_counter\x18\b \x01(\x04R\x14activeDecoderCounter\x122\n" +
	"\x15total_decoder_counter\x18\t \x01(\x04R\x13totalDecoderCounter\x12?\n" +
	"\x1cactive_audio_decoder_counter\x18\x18 \x01(\x04R\x19activeAudioDecoderCounter\x124\n" +
	"\tcapturers\x18\n" +
	" \x03(\v2\x16.messages.CaptureStatsR\tcapturers\x12(\n" +
	"\x10sip_call_counter\x18\v \x01(\x04R\x0esipCallCounter\x122\n" +
	"\x15resip_message_counter\x18\f \x01(\x04R\x13resipMessageCounter\x129\n" +
	"\x19resip_sip_message_counter\x18\r \x01(\x04R\x16resipSipMessageCounter\x12.\n" +
	"\x13mem_allocated_bytes\x18\x0e \x01(\x04R\x11memAllocatedBytes\x12\"\n" +
	"\rmem_heap_size\x18\x0f \x01(\x04R\vmemHeapSize\x125\n" +
	"\x17mem_pageheap_free_bytes\x18\x10 \x01(\x04R\x14memPageheapFreeBytes\x12&\n" +
	"\x0fmem_alloc_count\x18\x11 \x01(\x04R\rmemAllocCount\x12$\n" +
	"\x0emem_free_count\x18\x12 \x01(\x04R\fmemFreeCount\x12+\n" +
	"\x12mem_allocs_per_sec\x18\x13 \x01(\x01R\x0fmemAllocsPerSec\x12)\n" +
	"\x11mem_frees_per_sec\x18\x14 \x01(\x01R\x0ememFreesPerSec\x12(\n" +
	"\x10cpu_user_seconds\x18\x15 \x01(\x01R\x0ecpuUserSeconds\x12,\n" +
	"\x12cpu_system_seconds\x18\x16 \x01(\x01R\x10cpuSystemSeconds\x12*\n" +
	"\x11cpu_usage_percent\x18\x17 \x01(\x01R\x0fcpuUsagePercent\"\xa0\x01\n" +
	"\aSipPeer\x12\x10\n" +
	"\x03aor\x18\x01 \x01(\tR\x03aor\x12\x1d\n" +
	"\n" +
	"user_agent\x18\x02 \x01(\tR\tuserAgent\x128\n" +
	"\rrtp_addresses\x18\x03 \x03(\v2\x13.messages.IpAddressR\frtpAddresses\x12\x16\n" +
	"\x06codecs\x18\x04 \x01(\tR\x06codecs\x12\x12\n" +
	"\x04ssrc\x18\x05 \x01(\rR\x04ssrc\"\xe5\x01\n" +
	"\fSipCallStart\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12)\n" +
	"\x06caller\x18\x03 \x01(\v2\x11.messages.SipPeerR\x06caller\x12)\n" +
	"\x06callee\x18\x04 \x01(\v2\x11.messages.SipPeerR\x06callee\x12\x1d\n" +
	"\n" +
	"setup_code\x18\x05 \x01(\rR\tsetupCode\x12)\n" +
	"\x10invite_timestamp\x18\x06 \x01(\x04R\x0finviteTimestamp\"\xdc\x01\n" +
	"\n" +
	"SipCallEnd\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12;\n" +
	"\rbye_direction\x18\x03 \x01(\x0e2\x16.messages.SipDirectionR\fbyeDirection\x12%\n" +
	"\x0eresponse_codes\x18\x04 \x03(\rR\rresponseCodes\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x04R\bduration\x12\x17\n" +
	"\ahas_bye\x18\x06 \x01(\bR\x06hasBye\"\xf0\x01\n" +
	"\vSipReinvite\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12\x1d\n" +
	"\n" +
	"is_request\x18\x03 \x01(\bR\tisRequest\x124\n" +
	"\tdirection\x18\x04 \x01(\x0e2\x16.messages.SipDirectionR\tdirection\x124\n" +
	"\fupdated_peer\x18\x05 \x01(\v2\x11.messages.SipPeerR\vupdatedPeer\x12\x1f\n" +
	"\vraw_message\x18\x06 \x01(\tR\n" +
	"rawMessage\"\xa5\x03\n" +
	"\rSipCallFailed\x12\x17\n" +
	"\acall_id\x18\x01 \x01(\tR\x06callId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x04R\ttimestamp\x12)\n" +
	"\x06caller\x18\x03 \x01(\v2\x11.messages.SipPeerR\x06caller\x12)\n" +
	"\x06callee\x18\x04 \x01(\v2\x11.messages.SipPeerR\x06callee\x12)\n" +
	"\x10invite_timestamp\x18\x05 \x01(\x04R\x0finviteTimestamp\x126\n" +
	"\x06reason\x18\x06 \x01(\x0e2\x1e.messages.SipCallFailed.ReasonR\x06reason\x12#\n" +
	"\rresponse_code\x18\a \x01(\rR\fresponseCode\x12#\n" +
	"\rreason_phrase\x18\b \x01(\tR\freasonPhrase\"Z\n" +
	"\x06Reason\x12\x12\n" +
	"\x0eREASON_UNKNOWN\x10\x00\x12\x13\n" +
	"\x0fREASON_REJECTED\x10\x01\x12\x13\n" +
	"\x0fREASON_CANCELED\x10\x02\x12\x12\n" +
	"\x0eREASON_TIMEOUT\x10\x03\"\xd4\x05\n" +
	"\x05Event\x125\n" +
	"\rstream_report\x18\x01 \x01(\v2\x10.messages.StreamR\fstreamReport\x128\n" +
	"\fstream_start\x18\x02 \x01(\v2\x15.messages.StreamStartR\vstreamStart\x12;\n" +
	"\rstream_finish\x18\x03 \x01(\v2\x16.messages.StreamFinishR\fstreamFinish\x12;\n" +
	"\rcapture_stats\x18\x04 \x01(\v2\x16.messages.CaptureStatsR\fcaptureStats\x128\n" +
	"\fstream_ghost\x18\x05 \x01(\v2\x15.messages.StreamGhostR\vstreamGhost\x12C\n" +
	"\x0einstance_stats\x18\x06 \x01(\v2\x1c.messages.InstanceStatisticsR\rinstanceStats\x12<\n" +
	"\x0esip_call_start\x18\a \x01(\v2\x16.messages.SipCallStartR\fsipCallStart\x126\n" +
	"\fsip_call_end\x18\b \x01(\v2\x14.messages.SipCallEndR\n" +
	"sipCallEnd\x128\n" +
	"\fsip_reinvite\x18\t \x01(\v2\x15.messages.SipReinviteR\vsipReinvite\x12?\n" +
	"\x0fsip_call_failed\x18\n" +
	" \x01(\v2\x17.messages.SipCallFailedR\rsipCallFailed\x128\n" +
	"\fstream_audio\x18\v \x01(\v2\x15.messages.StreamAudioR\vstreamAudio\x126\n" +
	"\fesp_sa_event\x18\f \x01(\v2\x14.messages.EspSaEventR\n" +
	"espSaEvent\"-\n" +
	"\n" +
	"TrackEntry\x12\x1f\n" +
	"\vsip_pattern\x18\x01 \x01(\tR\n" +
	"sipPattern\"\xaa\x01\n" +
	"\aCommand\x12$\n" +
	"\x02op\x18\x01 \x01(\x0e2\x14.messages.Command.OpR\x02op\x12.\n" +
	"\aentries\x18\x02 \x03(\v2\x14.messages.TrackEntryR\aentries\"I\n" +
	"\x02Op\x12\r\n" +
	"\tTRACK_ADD\x10\x00\x12\x10\n" +
	"\fTRACK_REMOVE\x10\x01\x12\x11\n" +
	"\rTRACK_REPLACE\x10\x02\x12\x0f\n" +
	"\vTRACK_QUERY\x10\x03\"\x8d\x01\n" +
	"\n" +
	"CommandAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12.\n" +
	"\acurrent\x18\x03 \x03(\v2\x14.messages.TrackEntryR\acurrent\x12)\n" +
	"\x10affected_streams\x18\x04 \x01(\rR\x0faffectedStreams*_\n" +
	"\fSipDirection\x12\x13\n" +
	"\x0fSIP_DIR_UNKNOWN\x10\x00\x12\x1c\n" +
	"\x18SIP_DIR_CALLER_TO_CALLEE\x10\x01\x12\x1c\n" +
	"\x18SIP_DIR_CALLEE_TO_CALLER\x10\x02b\x06proto3"

var (
	file_capturemessage_proto_rawDescOnce sync.Once
	file_capturemessage_proto_rawDescData []byte
)

func file_capturemessage_proto_rawDescGZIP() []byte {
	file_capturemessage_proto_rawDescOnce.Do(func() {
		file_capturemessage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_capturemessage_proto_rawDesc), len(file_capturemessage_proto_rawDesc)))
	})
	return file_capturemessage_proto_rawDescData
}

var file_capturemessage_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_capturemessage_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_capturemessage_proto_goTypes = []any{
	(SipDirection)(0),          // 0: messages.SipDirection
	(IpAddress_Family)(0),      // 1: messages.IpAddress.Family
	(SipCallFailed_Reason)(0),  // 2: messages.SipCallFailed.Reason
	(Command_Op)(0),            // 3: messages.Command.Op
	(*IpAddress)(nil),          // 4: messages.IpAddress
	(*EspSaEvent)(nil),         // 5: messages.EspSaEvent
	(*StreamId)(nil),           // 6: messages.StreamId
	(*MetricStats)(nil),        // 7: messages.MetricStats
	(*CaptureStats)(nil),       // 8: messages.CaptureStats
	(*Stream)(nil),             // 9: messages.Stream
	(*StreamStart)(nil),        // 10: messages.StreamStart
	(*StreamFinish)(nil),       // 11: messages.StreamFinish
	(*StreamGhost)(nil),        // 12: messages.StreamGhost
	(*StreamAudio)(nil),        // 13: messages.StreamAudio
	(*InstanceStatistics)(nil), // 14: messages.InstanceStatistics
	(*SipPeer)(nil),            // 15: messages.SipPeer
	(*SipCallStart)(nil),       // 16: messages.SipCallStart
	(*SipCallEnd)(nil),         // 17: messages.SipCallEnd
	(*SipReinvite)(nil),        // 18: messages.SipReinvite
	(*SipCallFailed)(nil),      // 19: messages.SipCallFailed
	(*Event)(nil),              // 20: messages.Event
	(*TrackEntry)(nil),         // 21: messages.TrackEntry
	(*Command)(nil),            // 22: messages.Command
	(*CommandAck)(nil),         // 23: messages.CommandAck
	(*Stream_SipInfo)(nil),     // 24: messages.Stream.SipInfo
	(*Stream_EchoPeak)(nil),    // 25: messages.Stream.EchoPeak
	(*Stream_DtxInfo)(nil),     // 26: messages.Stream.DtxInfo
}
var file_capturemessage_proto_depIdxs = []int32{
	1,  // 0: messages.IpAddress.family:type_name -> messages.IpAddress.Family
	4,  // 1: messages.EspSaEvent.dst:type_name -> messages.IpAddress
	4,  // 2: messages.StreamId.src:type_name -> messages.IpAddress
	4,  // 3: messages.StreamId.dst:type_name -> messages.IpAddress
	6,  // 4: messages.Stream.stream_id:type_name -> messages.StreamId
	24, // 5: messages.Stream.sip:type_name -> messages.Stream.SipInfo
	25, // 6: messages.Stream.echolist:type_name -> messages.Stream.EchoPeak
	26, // 7: messages.Stream.dtx_info:type_name -> messages.Stream.DtxInfo
	7,  // 8: messages.Stream.jitter:type_name -> messages.MetricStats
	7,  // 9: messages.Stream.rtt:type_name -> messages.MetricStats
	7,  // 10: messages.Stream.mos_network:type_name -> messages.MetricStats
	7,  // 11: messages.Stream.mos_sevana:type_name -> messages.MetricStats
	6,  // 12: messages.StreamStart.stream_id:type_name -> messages.StreamId
	6,  // 13: messages.StreamFinish.stream_id:type_name -> messages.StreamId
	9,  // 14: messages.StreamFinish.report:type_name -> messages.Stream
	6,  // 15: messages.StreamGhost.stream_id:type_name -> messages.StreamId
	6,  // 16: messages.StreamAudio.stream_id:type_name -> messages.StreamId
	8,  // 17: messages.InstanceStatistics.capturers:type_name -> messages.CaptureStats
	4,  // 18: messages.SipPeer.rtp_addresses:type_name -> messages.IpAddress
	15, // 19: messages.SipCallStart.caller:type_name -> messages.SipPeer
	15, // 20: messages.SipCallStart.callee:type_name -> messages.SipPeer
	0,  // 21: messages.SipCallEnd.bye_direction:type_name -> messages.SipDirection
	0,  // 22: messages.SipReinvite.direction:type_name -> messages.SipDirection
	15, // 23: messages.SipReinvite.updated_peer:type_name -> messages.SipPeer
	15, // 24: messages.SipCallFailed.caller:type_name -> messages.SipPeer
	15, // 25: messages.SipCallFailed.callee:type_name -> messages.SipPeer
	2,  // 26: messages.SipCallFailed.reason:type_name -> messages.SipCallFailed.Reason
	9,  // 27: messages.Event.stream_report:type_name -> messages.Stream
	10, // 28: messages.Event.stream_start:type_name -> messages.StreamStart
	11, // 29: messages.Event.stream_finish:type_name -> messages.StreamFinish
	8,  // 30: messages.Event.capture_stats:type_name -> messages.CaptureStats
	12, // 31: messages.Event.stream_ghost:type_name -> messages.StreamGhost
	14, // 32: messages.Event.instance_stats:type_name -> messages.InstanceStatistics
	16, // 33: messages.Event.sip_call_start:type_name -> messages.SipCallStart
	17, // 34: messages.Event.sip_call_end:type_name -> messages.SipCallEnd
	18, // 35: messages.Event.sip_reinvite:type_name -> messages.SipReinvite
	19, // 36: messages.Event.sip_call_failed:type_name -> messages.SipCallFailed
	13, // 37: messages.Event.stream_audio:type_name -> messages.StreamAudio
	5,  // 38: messages.Event.esp_sa_event:type_name -> messages.EspSaEvent
	3,  // 39: messages.Command.op:type_name -> messages.Command.Op
	21, // 40: messages.Command.entries:type_name -> messages.TrackEntry
	21, // 41: messages.CommandAck.current:type_name -> messages.TrackEntry
	42, // [42:42] is the sub-list for method output_type
	42, // [42:42] is the sub-list for method input_type
	42, // [42:42] is the sub-list for extension type_name
	42, // [42:42] is the sub-list for extension extendee
	0,  // [0:42] is the sub-list for field type_name
}

func init() { file_capturemessage_proto_init() }
func file_capturemessage_proto_init() {
	if File_capturemessage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_capturemessage_proto_rawDesc), len(file_capturemessage_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_capturemessage_proto_goTypes,
		DependencyIndexes: file_capturemessage_proto_depIdxs,
		EnumInfos:         file_capturemessage_proto_enumTypes,
		MessageInfos:      file_capturemessage_proto_msgTypes,
	}.Build()
	File_capturemessage_proto = out.File
	file_capturemessage_proto_goTypes = nil
	file_capturemessage_proto_depIdxs = nil
}
