#!/usr/bin/env bash
# Run the bundled vq-db in the foreground, in-place, against a local SQLite
# database. No install, no root, nothing under /opt touched — everything lives
# next to this script inside the unpacked bundle. The dashboard is embedded in
# the binary and served at /ui/ (the root redirects there).
#
# With no arguments it generates (once) a run_test.cfg beside this script:
# console logging, SQLite DB + pid + csv under ./.run_test/, and the default
# vq-core bus ports (SUB 9125 / control 9127) with a DISTINCT test dashboard
# port (9156) so it never clashes with an installed service. Pass a config path
# to use that instead; extra args after the config are forwarded to vq-db.
#
# Usage (from the unpacked bundle dir):
#   ./run_test.sh                          # generated local config
#   ./run_test.sh /path/to/vq-monitor.cfg  # use an explicit config instead
#   LOG_LEVEL=debug ./run_test.sh          # override log level
#   DASH_PORT=9200 ./run_test.sh           # override the test dashboard port
#   SUB_PORT=9125 CTRL_PORT=9127 ./run_test.sh   # point at a specific vq-core
#
# Then open http://localhost:9156/ (the dashboard) or curl the API, e.g.
#   curl -s http://localhost:9156/version
# The daemon keeps retrying its SUB connection to vq-core, so it serves the
# dashboard/API even with no vq-core running (an empty or pre-seeded DB).
# Stop with Ctrl-C. Delete .run_test/ to start from a clean database.
set -euo pipefail

SELF_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN="$SELF_DIR/bin/vq-db"
[ -x "$BIN" ] || { echo "vq-db binary not found at $BIN" >&2; exit 1; }

# An explicit config path as the first arg uses that file instead of generating.
CFG=""
if [ "$#" -gt 0 ] && [ -f "$1" ]; then
    CFG="$1"
    shift
fi

if [ -z "$CFG" ]; then
    CFG="$SELF_DIR/run_test.cfg"
    DATA_DIR="$SELF_DIR/.run_test"
    mkdir -p "$DATA_DIR"
    if [ ! -f "$CFG" ]; then
        cat > "$CFG" <<EOF
# Generated by run_test.sh — local in-place test config. Edit freely; delete to
# regenerate with defaults.
logging:
    level:    ${LOG_LEVEL:-info}
    db:       ''
    console:  true

server:
    instance:
        id:                 test_agent
        name:               run_test (go)
    zeromq-port:            ${SUB_PORT:-9125}
    zeromq-control-port:    ${CTRL_PORT:-9127}
    ghost-stream-timeout:   120s
    pidfile-db:             $DATA_DIR/vq-db.pid

dashboard:
    port:               ${DASH_PORT:-9156}
    max-streams:        40
    good-mos-threshold: 3.6

database:
    engine:             sqlite3
    connection:         "db=$DATA_DIR/vq-monitor.sqlite"
    csv:                $DATA_DIR/vq-db.csv
EOF
        echo ">> generated $CFG"
    fi
fi

# LOG_LEVEL overrides the config's level for both generated and explicit configs.
if [ -n "${LOG_LEVEL:-}" ]; then
    set -- --log-level "$LOG_LEVEL" "$@"
fi

echo ">> $BIN --config $CFG"
exec "$BIN" --config "$CFG" "$@"
